version: '3.7'

services:
  app1-apache:
    image: demo-app1-apache
    volumes:
      - ./app1:/var/www/html
    ports:
      - '8080:80'
    environment:
      - PHP_FPM_ADDRESS=app1-php:9000
    depends_on:
      - app1-php
  app1-php:
    image: php-fpm-ubuntu2004
    volumes:
      - ./app1:/var/www/html
    depends_on:
      - db
  db:
    image: demo-db

